FROM ubuntu:latest

ENV TZ=Europe/Moscow

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get install -y python3-pip python3-django net-tools postgresql-client bind9-utils dnsutils screen nginx curl nano

WORKDIR /lib_catalog/

COPY ./lib_catalog/ /lib_catalog/

ADD backend_nginx.conf /etc/nginx/nginx.conf

RUN pip install asgiref Django django-cors-headers django-filter djangorestframework lxml python-docx pytz sqlparse psycopg2-binary

EXPOSE 8001

ENV CI=true

COPY backend_start.sh /usr/local/bin/backend_start.sh

CMD ["/bin/bash", "/usr/local/bin/backend_start.sh"]

