---
- name: Task 2
  hosts: nodes

  tasks:
     - name: Remove httpd
       package:
         name: httpd
         state: absent
  
     - name: Remove /var/www/html/index.html
       file:
         path: "/var/www/html/index.html"
         state: absent

     - name: firewalld started
       service:
         name: firewalld
         state: started

     - name: close http
       firewalld:
         service: http
         permanent: true
         state: disabled
       notify:
       - Restart firewalld
     

  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted 
