- name: Task 1
  hosts: nodes

  tasks:
     - name: Install httpd
       package:
         name: httpd
         state: present
         update_cache: yes

     - name: Start httpd
       ansible.builtin.systemd:
         state: started
         enabled: yes
         name: httpd

     - name: Creating index /var/www/html/index.html
       copy:
         dest: "/var/www/html/index.html"
         content: "Welcome to my web server"
         owner: apache
         group: apache
         mode: 0644 

     - name: check firewalld status
       service:
         name: firewalld
         state: started 
         enabled: yes

     - name: permit http
       firewalld:
         service: http
         permanent: yes
         state: enabled
       notify:
       - Restart firewalld



  handlers:
     - name: Restart firewalld
       service:
         name: firewalld
         state: restarted
